jobs:
  build:
    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Change to server directory
        run: cd server

      - name: Install dependencies
        run: npm install
        working-directory: server # 🔥 Tambahkan ini!

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
        working-directory: server # 🔥 Tambahkan ini!

      - name: Restart PM2
        run: pm2 restart backendAPI
        working-directory: server # 🔥 Tambahkan ini!
